name: EB deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
         python test_application.py
deploy:
  needs:
    --build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ASIAQUZ4GWGOJWQDPHUK
      AWS_SECRET_ACCESS_KEY: LgWjj3w+B35LpZ836IfLG3YOL8hymSiLvhanLNX+
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli 
      - name: Init EB CLI
        run: |
           eb init --platform ${{secrets.AWS_PLATFORM}} --region ${{secrets.AWS_DEFAULT_REGION }}
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
